# 1. Project Information
site_name: My College Notes
site_url: https://aviteshmurmu19.github.io/mkdocs-tutorial/ # Your actual site URL
site_author: Avitesh Murmu
site_description: "A personal collection of college lecture notes."

# Add this at the top level of your mkdocs.yml
exclude_docs: |
  - _TEMPLATES/

# 2. Theme Configuration
theme:
  name: material
  logo: assets/RT Logo.png
  favicon: assets/RT Logo.ico
  font:
    text: Poppins
  features:
    - navigation.footer
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: pink
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: pink

# 3. Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

# 4. Plugins
plugins:
  - search
  - tags
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "34vw"

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js