[workspace]
authors = ["Avitesh Murmu <Aviteshmurmu19@gmail.com>"]
channels = ["conda-forge"]
name = "WebNotes"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
mkdocs-material = ">=9.6.17,<10"
ipykernel = ">=6.30.1,<7"

[pypi-dependencies]
jinja2 = "*"
markdown = "*"
mkdocs = "*"
mkdocs-material = "*"
mkdocs-material-extensions = "*"
pygments = "*"
pymdown-extensions = "*"
babel = "*"
colorama = "*"
paginate = "*"
regex = ">=2025.7.34, <2026"
requests = "*"
mkdocs-glightbox = ">=0.4.0, <0.5"
mkdocs-get-deps = "*"
mkdocs-git-committers-plugin = ">=0.2.3, <0.3"
mkdocs-git-revision-date-localized-plugin = ">=1.4.7, <2"
mkdocs-rss-plugin = ">=1.17.3, <2"
mkdocs-minify-plugin = ">=0.8.0, <0.9"
mkdocs-awesome-nav = ">=3.1.2, <4"
