[workspace]
authors = ["Avitesh Murmu <Aviteshmurmu19@gmail.com>"]
channels = ["conda-forge"]
name = "WebNotes"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
mkdocs-material = ">=9.6.17,<10"
ipykernel = ">=6.30.1,<7"
